version: '3.12'

services:
  crops-disease-app:
    build:
      context: .
      args:
        TORCH_DEVICE: "cpu"
    container_name: crops-disease-prediction
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models:ro
      - ./uploads:/app/uploads
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: crops-disease-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - crops-disease-app
    restart: unless-stopped
    profiles:
      - production

  crops-disease-app-gpu:
    build:
      context: .
      args:
        TORCH_DEVICE: "gpu"
    container_name: crops-disease-prediction-gpu
    ports:
      - "8502:8501"
    volumes:
      - ./models:/app/models:ro
      - ./uploads:/app/uploads
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - gpu
